package com.paypal.risk.idi.models.session;

import java.util.Map;

import com.ebay.kernel.logger.Logger;
import com.paypal.risk.idi.variables.function.Contexts;
import com.paypal.risk.idi.variables.AbstractBaseVariable;
import static com.paypal.risk.idi.models.session.SessionVariableRepository.*;


public class $classname$  {

  public static Logger logger = Logger.getInstance($classname$.class);
  
  public $abstractsegment$ getSegment(Map<String, Object> ctxt) throws Exception{
    
    $getsegment$
  }
}